// Automated D1 -> R2 backup, run daily by a Cron Trigger separate from
// ingestion's (see worker/index.ts's scheduled handler and wrangler.jsonc's
// triggers.crons) — CLAUDE.md's "prod database is the only copy that
// matters" section treats this as non-negotiable, not optional polish.

export interface TableDump {
  table: string;
  columns: string[];
  rows: Record<string, unknown>[];
}

function sqlValue(value: unknown): string {
  if (value === null || value === undefined) return "NULL";
  if (typeof value === "number") return String(value);
  return `'${String(value).replace(/'/g, "''")}'`;
}

/**
 * Pure fold: table snapshots -> a restorable SQL text of plain INSERTs.
 * Doesn't include schema (migrations own that — apply them first, then this
 * file, to restore). Explicit column lists rather than `SELECT *` ordering,
 * same reasoning as scripts/import-mbox.ts's sqlString/INSERT shape.
 *
 * No provenance header here deliberately: this is shared with
 * scripts/db-export.ts's manual, human-triggered export, which isn't the
 * daily Cron Trigger — each caller prepends its own header describing where
 * its dump actually came from.
 */
export function buildBackupSql(tables: TableDump[]): string {
  const lines: string[] = ["-- Restore against a migrated (empty) database: apply migrations first, then this file."];
  for (const { table, columns, rows } of tables) {
    if (rows.length === 0) continue;
    lines.push(`-- ${table} (${rows.length} rows)`);
    for (const row of rows) {
      const values = columns.map((col) => sqlValue(row[col]));
      lines.push(`INSERT INTO ${table} (${columns.join(", ")}) VALUES (${values.join(", ")});`);
    }
  }
  return `${lines.join("\n")}\n`;
}

// Exported so scripts/db-export.ts (the manual pre-migration habit) can dump
// the same tables the same way, without shelling out to `wrangler d1 export`
// — which refuses to touch a database with an FTS5 virtual table at all
// (letters_fts, since migration 0001). Deliberately excludes letters_fts
// itself: it's a derived index, rebuilt by migrations/0001's triggers on
// INSERT, not primary data.
export const BACKUP_TABLES: { table: string; columns: string[] }[] = [
  { table: "letters", columns: ["id", "date", "text", "meditation_title", "meditation_url", "gmail_message_id", "created_at"] },
  { table: "letter_photos", columns: ["id", "letter_id", "r2_key", "mime_type", "caption"] },
  { table: "review_queue", columns: ["id", "gmail_message_id", "reason", "received_date", "raw_text", "status", "created_at"] },
  { table: "ingestion_state", columns: ["key", "value"] },
  { table: "comments", columns: ["id", "letter_id", "device_id", "ip_hash", "author_name", "body", "status", "created_at"] },
  { table: "comment_bans", columns: ["device_id", "reason", "banned_at"] },
  { table: "settings", columns: ["key", "value"] },
];

export async function runBackup(env: Env): Promise<{ key: string; rowCounts: Record<string, number> }> {
  const dumps: TableDump[] = [];
  const rowCounts: Record<string, number> = {};

  for (const { table, columns } of BACKUP_TABLES) {
    const { results } = await env.DB.prepare(`SELECT ${columns.join(", ")} FROM ${table}`).all<Record<string, unknown>>();
    const rows = results ?? [];
    dumps.push({ table, columns, rows });
    rowCounts[table] = rows.length;
  }

  const sql = `-- Automated D1 backup, generated by the daily backup Cron Trigger.\n${buildBackupSql(dumps)}`;
  const key = `prod-${new Date().toISOString().replace(/[:.]/g, "-")}.sql`;
  await env.BACKUPS.put(key, sql, { httpMetadata: { contentType: "application/sql" } });

  return { key, rowCounts };
}
